export interface ExampleProject {
  id: string;
  title: string;
  tagline: string;
  description: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  estimatedHours: string;
  suggestedBoard: string;
  suggestedSensors: string[];
  idea: string;
  icon: string;
  category: string;
}

export const EXAMPLES: ExampleProject[] = [
  {
    id: "smart-garden",
    title: "Smart Garden Irrigation",
    tagline: "Automatically waters your plants based on soil moisture",
    description: "Build an automated irrigation system that measures soil moisture and temperature, then waters plants when needed. Displays data on an LCD and can be controlled from a smartphone via Bluetooth.",
    difficulty: "Beginner",
    estimatedHours: "8-10",
    suggestedBoard: "Arduino Uno",
    suggestedSensors: ["Soil Moisture Sensor", "DHT11", "16×2 LCD", "Relay Module", "Water Pump"],
    idea: "Smart garden irrigation system that waters plants automatically based on soil moisture readings",
    icon: "🌱",
    category: "Environmental",
  },
  {
    id: "weather-station",
    title: "Weather Monitoring Station",
    tagline: "Track temperature, humidity, pressure, and air quality",
    description: "Create a desktop weather station that measures temperature, humidity, barometric pressure, and air quality (PM2.5). Data is displayed on an OLED screen and logged to an SD card for analysis.",
    difficulty: "Beginner",
    estimatedHours: "10-12",
    suggestedBoard: "Arduino Uno",
    suggestedSensors: ["DHT22", "BMP180", "MQ-135", "OLED Display", "MicroSD Card Module"],
    idea: "Desktop weather station that measures temperature, humidity, pressure, and air quality with data logging",
    icon: "🌤️",
    category: "Environmental",
  },
  {
    id: "smart-water-meter",
    title: "Smart Water Flow Meter",
    tagline: "Monitor household water consumption in real time",
    description: "Build a water flow meter that tracks consumption, detects leaks, and sends alerts when usage exceeds thresholds. Includes a mobile dashboard via WiFi and automatic shut-off valve control.",
    difficulty: "Intermediate",
    estimatedHours: "15-20",
    suggestedBoard: "ESP32",
    suggestedSensors: ["Water Flow Sensor", "Solenoid Valve", "OLED Display", "Buzzer", "ACS712 Current Sensor"],
    idea: "Smart water meter that tracks household consumption, detects leaks, and controls a shut-off valve via WiFi",
    icon: "💧",
    category: "Environmental",
  },
  {
    id: "home-security",
    title: "IoT Home Security System",
    tagline: "Motion detection, door sensors, and camera alerts",
    description: "Build a complete home security system with PIR motion sensors, magnetic door contacts, a camera module, and an alarm. Sends push notifications and can be armed/disarmed via keypad or mobile app.",
    difficulty: "Intermediate",
    estimatedHours: "20-25",
    suggestedBoard: "ESP32",
    suggestedSensors: ["PIR Motion Sensor", "Magnetic Reed Switch", "Camera Module OV2640", "Buzzer", "4×4 Keypad", "SG90 Servo"],
    idea: "Home security system with motion detection, door sensors, camera, and mobile alerts via WiFi",
    icon: "🛡️",
    category: "Security",
  },
  {
    id: "smart-lighting",
    title: "Smart Lighting System",
    tagline: "Voice-controlled, dimmable, colour-changing lights",
    description: "Control RGB LED strips with voice commands via Bluetooth or WiFi. Includes a mobile app interface, preset scenes (Study, Party, Sleep), automatic brightness based on ambient light, and energy usage tracking.",
    difficulty: "Beginner",
    estimatedHours: "6-8",
    suggestedBoard: "ESP8266",
    suggestedSensors: ["RGB LED Strip", "LDR Sensor", "HC-05 Bluetooth", "IR Receiver", "MOSFET IRF520"],
    idea: "Voice and app controlled smart lighting system with RGB strips, dimming, and ambient light sensing",
    icon: "💡",
    category: "Home Automation",
  },
  {
    id: "health-monitor",
    title: "Health Monitoring Patch",
    tagline: "Track heart rate, SpO2, and body temperature",
    description: "Wearable health monitor that measures heart rate (BPM), blood oxygen saturation (SpO2), and body temperature. Displays on a small OLED and syncs data to a phone via Bluetooth for health logging.",
    difficulty: "Intermediate",
    estimatedHours: "12-16",
    suggestedBoard: "Arduino Nano",
    suggestedSensors: ["MAX30102", "LM35", "OLED Display", "HC-05 Bluetooth", "Vibration Motor"],
    idea: "Wearable health monitor that tracks heart rate, SpO2, and body temperature with Bluetooth sync",
    icon: "❤️",
    category: "Health",
  },
  {
    id: "rfid-door-lock",
    title: "RFID Door Lock System",
    tagline: "Keyless entry with RFID cards and PIN backup",
    description: "Secure door lock system that opens with authorized RFID cards or a PIN code. Features an admin mode to add/remove cards, an event log of entries, and a buzzer alarm for tamper attempts.",
    difficulty: "Beginner",
    estimatedHours: "6-8",
    suggestedBoard: "Arduino Uno",
    suggestedSensors: ["RC522 RFID Module", "4×4 Keypad", "Solenoid Door Lock", "OLED Display", "Buzzer"],
    idea: "RFID-based door lock with PIN backup, admin card management, and entry logging",
    icon: "🔐",
    category: "Security",
  },
  {
    id: "solar-tracker",
    title: "Dual-Axis Solar Tracker",
    tagline: "Maximise solar panel efficiency with light tracking",
    description: "Build a dual-axis solar tracker that follows the sun using LDR sensors and servo motors. Includes real-time power output display, manual override, and data logging to SD card for efficiency analysis.",
    difficulty: "Advanced",
    estimatedHours: "20-25",
    suggestedBoard: "Arduino Mega",
    suggestedSensors: ["4× LDR Sensor", "2× SG90 Servo", "OLED Display", "ACS712 Current Sensor", "MicroSD Card Module"],
    idea: "Dual-axis solar tracker that follows sunlight using LDRs and servos with power output display",
    icon: "☀️",
    category: "Energy",
  },
  {
    id: "smart-fish-tank",
    title: "Smart Fish Tank Manager",
    tagline: "Automated feeding, temperature control, and water quality",
    description: "Complete fish tank management system that monitors water temperature, pH, and turbidity. Automatically dispenses food at scheduled times, controls a heater, and sends alerts when parameters go out of range.",
    difficulty: "Intermediate",
    estimatedHours: "15-18",
    suggestedBoard: "ESP32",
    suggestedSensors: ["DS18B20", "pH Sensor", "Turbidity Sensor", "SG90 Servo", "Relay Module", "OLED Display"],
    idea: "Automated fish tank manager that monitors water quality, controls feeding and temperature with WiFi alerts",
    icon: "🐠",
    category: "Environmental",
  },
  {
    id: "smart-bin",
    title: "Smart Waste Segregation Bin",
    tagline: "Automatically sorts waste into metal, plastic, and organic",
    description: "Intelligent waste bin that uses sensors to detect and sort waste into metal, plastic, and organic compartments. Includes fill-level monitoring, compaction, and a mobile notification when full.",
    difficulty: "Advanced",
    estimatedHours: "25-30",
    suggestedBoard: "Arduino Mega",
    suggestedSensors: ["IR Sensor", "Metal Detector", "SG90 Servo", "HC-SR04 Ultrasonic", "Load Cell HX711", "Buzzer"],
    idea: "Smart waste bin that automatically sorts metal, plastic, and organic waste with fill-level monitoring",
    icon: "♻️",
    category: "Environmental",
  },
  {
    id: "gesture-car",
    title: "Gesture-Controlled Robot Car",
    tagline: "Drive a robot using hand gestures and an accelerometer",
    description: "Build a robot car that responds to hand gestures using an accelerometer worn on your hand. Features obstacle avoidance, speed control, and a live camera feed transmitted over WiFi.",
    difficulty: "Advanced",
    estimatedHours: "20-25",
    suggestedBoard: "Raspberry Pi Pico",
    suggestedSensors: ["MPU6050", "HC-SR04", "L298N Motor Driver", "SG90 Servo", "Camera Module", "NRF24L01"],
    idea: "Gesture-controlled robot car using accelerometer hand gestures with obstacle avoidance and camera feed",
    icon: "🤖",
    category: "Robotics",
  },
  {
    id: "smart-fan",
    title: "Smart Cooling Fan",
    tagline: "Temperature and voice-controlled desk fan",
    description: "A desk fan that automatically adjusts speed based on room temperature, can be controlled by voice commands via Bluetooth, and shows real-time stats on an OLED display. Includes a sleep mode timer.",
    difficulty: "Beginner",
    estimatedHours: "6-8",
    suggestedBoard: "Arduino Uno",
    suggestedSensors: ["DHT11", "IR Receiver", "L298N Motor Driver", "OLED Display", "HC-05 Bluetooth"],
    idea: "Temperature and voice-controlled smart desk fan with auto speed adjustment and timer",
    icon: "🌀",
    category: "Home Automation",
  },
  {
    id: "plant-monitor",
    title: "Smart Plant Monitor",
    tagline: "Know exactly when your plants need water and light",
    description: "A compact device that tracks soil moisture, ambient light, and temperature for each plant. Sends reminders to your phone via Bluetooth when a plant needs watering or is getting too little light.",
    difficulty: "Beginner",
    estimatedHours: "4-6",
    suggestedBoard: "ESP8266",
    suggestedSensors: ["Soil Moisture Sensor", "LDR Sensor", "DHT11", "OLED Display"],
    idea: "Compact plant monitor that tracks soil moisture, light, and temperature with phone reminders",
    icon: "🌿",
    category: "Environmental",
  },
  {
    id: "parking-sensor",
    title: "Smart Parking Assistant",
    tagline: "Ultrasonic reverse parking sensor with distance display",
    description: "Car reverse parking assistant that measures distance using ultrasonic sensors, shows readings on an LED bar graph, and plays escalating beeps. Includes a buzzer and optional servo-based camera aim.",
    difficulty: "Beginner",
    estimatedHours: "5-7",
    suggestedBoard: "Arduino Nano",
    suggestedSensors: ["HC-SR04", "LED Bar Graph", "Buzzer", "TM1637 Display", "SG90 Servo"],
    idea: "Reverse parking assistant with ultrasonic distance sensing, LED display, and beeping alerts",
    icon: "🚗",
    category: "Automotive",
  },
  {
    id: "smart-agri",
    title: "Smart Agriculture Monitor",
    tagline: "Multi-sensor field monitoring for precision farming",
    description: "Agricultural monitoring system with multiple sensor nodes spread across a field. Measures soil moisture, temperature, humidity, and rainfall. Data is sent via LoRa to a central hub with solar-powered operation.",
    difficulty: "Advanced",
    estimatedHours: "30-35",
    suggestedBoard: "ESP32",
    suggestedSensors: ["Soil Moisture Sensor", "DHT22", "Rain Gauge", "LoRa Module", "Solar Panel", "BMP180"],
    idea: "Solar-powered agricultural field monitoring system with LoRa wireless sensor nodes and data hub",
    icon: "🌾",
    category: "Environmental",
  },
];
