import { Component, BoardSpec } from "./types";

export const COMPONENTS: Component[] = [
  // ── Boards (treated as components for the catalog) ──
  { id: "arduino-uno", name: "Arduino Uno", desc: "ATmega328P, 14 digital I/O, 6 analog inputs", category: "Board", icon: "Cpu", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 5, currentDrawMa: 50 },
  { id: "arduino-nano", name: "Arduino Nano", desc: "Compact ATmega328P, breadboard-friendly", category: "Board", icon: "Cpu", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 5, currentDrawMa: 40 },
  { id: "arduino-mega", name: "Arduino Mega", desc: "ATmega2560, 54 I/O, 16 analog, 4 UARTs", category: "Board", icon: "Cpu", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 5, currentDrawMa: 80 },
  { id: "arduino-pro-mini", name: "Arduino Pro Mini", desc: "Ultra-compact 3.3V/5V, no USB port", category: "Board", icon: "Cpu", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: "3.3-5", currentDrawMa: 25 },
  { id: "esp32", name: "ESP32", desc: "Dual-core WiFi + Bluetooth, 2 DACs, touch", category: "Board", icon: "Wifi", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 3.3, currentDrawMa: 80 },
  { id: "esp8266", name: "ESP8266 (NodeMCU)", desc: "Low-cost WiFi MCU, 11 I/O, Lua/C++", category: "Board", icon: "Wifi", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 3.3, currentDrawMa: 70 },
  { id: "rpi4", name: "Raspberry Pi 4", desc: "Quad-core 1.8 GHz, 4 GB RAM, GPIO 40-pin", category: "Board", icon: "Monitor", lang: "python", interface: "digital", pinsRequired: 0, voltage: 5, currentDrawMa: 600 },
  { id: "rpi-zero2", name: "Raspberry Pi Zero 2", desc: "Compact 1 GHz quad-core, WiFi, CSI port", category: "Board", icon: "Monitor", lang: "python", interface: "digital", pinsRequired: 0, voltage: 5, currentDrawMa: 350 },
  { id: "rpi-pico", name: "Raspberry Pi Pico", desc: "RP2040 dual-core, 26 GPIO, MicroPython", category: "Board", icon: "Cpu", lang: "both", interface: "digital", pinsRequired: 0, voltage: 3.3, currentDrawMa: 40 },
  { id: "stm32-bluepill", name: "STM32 Blue Pill", desc: "STM32F103C8T6, 72 MHz, 20 KB RAM", category: "Board", icon: "Cpu", lang: "cpp", interface: "digital", pinsRequired: 0, voltage: 3.3, currentDrawMa: 50 },

  // ── Environmental ──
  { id: "dht22", name: "DHT22", desc: "Digital temp & humidity, -40 to 80°C, ±0.5°C", category: "Environmental", icon: "Thermometer", lang: "both", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 1.5, calibrationNote: "±0.5°C, ±2% RH. Allow 2s between reads. Take 5 readings, discard first 2 (sensor warm-up), average the rest." },
  { id: "dht11", name: "DHT11", desc: "Basic temp & humidity, 0-50°C, ±2°C", category: "Environmental", icon: "Thermometer", lang: "both", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 0.5, calibrationNote: "±2°C, ±5% RH. Max 1 read/sec. Not reliable above 80% RH." },
  { id: "bme280", name: "BME280", desc: "Precision temp, humidity & barometric pressure", category: "Environmental", icon: "Gauge", lang: "both", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 0.003, i2cAddress: "0x76", calibrationNote: "±1°C, ±3% RH, ±1 hPa. Factory-calibrated. I2C address 0x76 (SDO high) or 0x77 (SDO low)." },
  { id: "ds18b20", name: "DS18B20", desc: "Waterproof digital temp sensor, 1-Wire, ±0.5°C", category: "Environmental", icon: "Droplets", lang: "both", interface: "onewire", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 1, calibrationNote: "±0.5°C, -55 to +125°C. Requires 4.7kΩ pull-up on data line. Parasitic power mode possible." },
  { id: "mq2", name: "MQ-2 Gas", desc: "LPG, propane, hydrogen, methane detection", category: "Environmental", icon: "Flame", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: 5, currentDrawMa: 150, calibrationNote: "Heater needs 48h burn-in for stable readings. Output is analog voltage ratio, not ppm — requires calibration gas for absolute values." },
  { id: "mq7", name: "MQ-7 CO", desc: "Carbon monoxide detection (100-1000 ppm)", category: "Environmental", icon: "Flame", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: 5, currentDrawMa: 150, calibrationNote: "Heater cycling: 60s high (5V) then 90s low (1.4V). Output drifts with temperature and humidity." },
  { id: "mq135", name: "MQ-135 Air", desc: "Air quality, NH₃, NOₓ, benzene, CO₂", category: "Environmental", icon: "Wind", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: 5, currentDrawMa: 150, calibrationNote: "Preheat 24-48h. Sensitive to multiple gases — can't distinguish specific compounds without additional filtering." },
  { id: "soil-moisture", name: "Soil Moisture", desc: "Capacitive/resistive soil water content", category: "Environmental", icon: "Droplet", lang: "both", interface: "analog", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 5, calibrationNote: "Resistive types corrode in ~3 months. Calibrate against known dry/wet soil samples; reading varies with soil type and temperature." },
  { id: "rain-sensor", name: "Rain Sensor", desc: "Detects rain/water on surface (digital + analog)", category: "Environmental", icon: "CloudRain", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: 5, currentDrawMa: 15 },
  { id: "ldr", name: "LDR / Photoresistor", desc: "Light-dependent resistor, voltage divider", category: "Environmental", icon: "Sun", lang: "both", interface: "analog", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 1 },
  { id: "uv-ml8511", name: "UV (ML8511)", desc: "UV intensity, analog output, 280-400 nm", category: "Environmental", icon: "Sun", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 0.3, calibrationNote: "Output is mW/cm². Requires 3.3V supply even with 5V board — use a regulator." },
  { id: "dust-gp2y1010", name: "Dust (GP2Y1010)", desc: "Optical dust/particulate sensor, PM2.5", category: "Environmental", icon: "Wind", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: 5, currentDrawMa: 20, calibrationNote: "Requires pulse-driven IR LED (10ms on, 0.32ms sampling). Output voltage ~0.5V clean air, ~3.5V max. Particle concentration is approximated, not precise PM2.5." },

  // ── Distance & Motion ──
  { id: "hc-sr04", name: "HC-SR04 Ultrasonic", desc: "2-400 cm range, 5V, echo pulse", category: "Distance & Motion", icon: "Ruler", lang: "both", interface: "digital", pinsRequired: 2, voltage: 5, currentDrawMa: 15, calibrationNote: "±3mm accuracy. Needs 5V even on 3.3V boards — use level shifter. Acoustic noise affects readings; take median of 5 samples." },
  { id: "pir", name: "PIR Motion", desc: "Passive IR, 3-7 m range, H/L output", category: "Distance & Motion", icon: "Footprints", lang: "both", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 0.065, calibrationNote: "~10s stabilization on power-up. Sensitivity and delay adjustable via potentiometers. False triggers from rapid temperature changes." },
  { id: "ir-obstacle", name: "IR Obstacle", desc: "IR emitter/detector, adjustable range", category: "Distance & Motion", icon: "AlertTriangle", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 20 },
  { id: "vl53l0x", name: "VL53L0X ToF", desc: "Laser time-of-flight, 2 m range, I²C", category: "Distance & Motion", icon: "Ruler", lang: "cpp", interface: "i2c", pinsRequired: 2, voltage: 3.3, currentDrawMa: 0.02, i2cAddress: "0x29", calibrationNote: "±3% accuracy. I2C address 0x29 (fixed — cannot change without a multiplexer for multiple units). Works poorly in direct sunlight." },
  { id: "rcwl0516", name: "RCWL-0516 Radar", desc: "Doppler microwave motion, 5-7 m range", category: "Distance & Motion", icon: "Radar", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 2.8 },
  { id: "rotary-encoder", name: "Rotary Encoder", desc: "Increangular position, 20 pulses/rev", category: "Distance & Motion", icon: "RefreshCw", lang: "cpp", interface: "digital", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 10 },
  { id: "mpu6050", name: "MPU-6050", desc: "3-axis gyro + 3-axis accelerometer, I²C", category: "Distance & Motion", icon: "Move3d", lang: "both", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 3.7, i2cAddress: "0x68", calibrationNote: "Default I2C 0x68 (AD0 low) or 0x69 (AD0 high). Gyro drifts over time — implement complementary filter or AHRS for stable orientation." },
  { id: "hmc5883l", name: "HMC5883L Compass", desc: "3-axis magnetometer, ±8 gauss, I²C", category: "Distance & Motion", icon: "Compass", lang: "cpp", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 0.1, i2cAddress: "0x1E", calibrationNote: "I2C 0x1E. Requires hard-iron calibration (rotate in figure-8 pattern). Easily distorted by nearby magnets and current-carrying wires." },

  // ── Output & Display ──
  { id: "lcd-i2c", name: "LCD 16x2 (I2C)", desc: "16×2 character display, I²C, 0x27/0x3F", category: "Output & Display", icon: "Monitor", lang: "both", interface: "i2c", pinsRequired: 2, voltage: 5, currentDrawMa: 60, i2cAddress: "0x27", calibrationNote: "Common I2C addresses 0x27 or 0x3F. Backlight draws ~50mA — consider PWM control for power saving." },
  { id: "oled-096", name: "OLED 0.96\" (I2C)", desc: "128×64 monochrome, SSD1306, I²C", category: "Output & Display", icon: "Monitor", lang: "both", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 20, i2cAddress: "0x3C", calibrationNote: "I2C 0x3C (default) or 0x3D. ~20mA typical draw. SPI version also available (faster refresh)." },
  { id: "tft-lcd", name: "TFT LCD (SPI)", desc: "1.8\" colour TFT, 160×128, ST7735", category: "Output & Display", icon: "Monitor", lang: "cpp", interface: "spi", pinsRequired: 6, voltage: "3.3-5", currentDrawMa: 80 },
  { id: "led", name: "LED", desc: "Standard 5 mm, 20 mA, current-limiting resistor needed", category: "Output & Display", icon: "Lightbulb", lang: "both", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 20 },
  { id: "rgb-led", name: "RGB LED", desc: "Common cathode/anode, 3 colours in one", category: "Output & Display", icon: "Palette", lang: "cpp", interface: "pwm", pinsRequired: 3, voltage: "3.3-5", currentDrawMa: 60 },
  { id: "ws2812b", name: "WS2812B LED Strip", desc: "Addressable RGB, 1-wire data, 5V", category: "Output & Display", icon: "Lightbulb", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: 5, currentDrawMa: 60, calibrationNote: "60mA per LED at full white. A 30-LED strip draws 1.8A — needs external 5V supply. Data line needs level shifter for 3.3V boards." },
  { id: "7-segment", name: "7-Segment Display", desc: "Common cathode/anode, 4-digit, TM1637", category: "Output & Display", icon: "Grid3x3", lang: "cpp", interface: "digital", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 30 },
  { id: "buzzer", name: "Buzzer", desc: "Piezo/passive, 2-4 kHz, PWM-capable", category: "Output & Display", icon: "Volume2", lang: "both", interface: "pwm", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 30 },
  { id: "servo-sg90", name: "Servo (SG90)", desc: "Micro servo, 0-180°, 4.8-6 V, PWM", category: "Output & Display", icon: "Rotate3d", lang: "both", interface: "pwm", pinsRequired: 1, voltage: 5, currentDrawMa: 250, calibrationNote: "Stall current ~700mA. Do not power from 5V pin on the board — use external 5V supply with common ground. Angle range may vary ±10° between units." },
  { id: "stepper", name: "Stepper Motor", desc: "28BYJ-48 5V, 4-phase, ULN2003 driver", category: "Output & Display", icon: "RotateCw", lang: "cpp", interface: "digital", pinsRequired: 4, voltage: 5, currentDrawMa: 250 },
  { id: "stepper-nema17", name: "NEMA 17 Stepper", desc: "Higher torque, A4988 driver, 12 V", category: "Output & Display", icon: "RotateCw", lang: "cpp", interface: "digital", pinsRequired: 2, voltage: 5, currentDrawMa: 50, calibrationNote: "Motor powered by external 12V supply (not from board). A4988 driver microstepping configurable via MS1/MS2/MS3 pins." },
  { id: "dc-motor-l298n", name: "DC Motor + L298N", desc: "Dual H-bridge, 7-12 V motor, 5 V logic", category: "Output & Display", icon: "Zap", lang: "cpp", interface: "digital", pinsRequired: 6, voltage: 5, currentDrawMa: 50, calibrationNote: "Motor supply 7-12V external. L298N has ~2V voltage drop — not efficient at low speeds. Consider L293D or TB6612 for battery projects." },
  { id: "relay", name: "Relay Module", desc: "1/2/4-channel, 10 A @ 250 V, optoisolated", category: "Output & Display", icon: "ToggleLeft", lang: "both", interface: "digital", pinsRequired: 1, voltage: 5, currentDrawMa: 70 },
  { id: "water-pump", name: "Mini Water Pump", desc: "3-6 V DC submersible, 120 L/h", category: "Output & Display", icon: "Droplet", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: 5, currentDrawMa: 500, calibrationNote: "Running dry damages the pump. Use a flow sensor or water level sensor as interlock. Requires motor driver or relay." },
  { id: "solenoid-lock", name: "Solenoid Door Lock", desc: "12 V electric strike, 1.2 A, push-pull", category: "Output & Display", icon: "Lock", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: 5, currentDrawMa: 20, calibrationNote: "12V/1.2A — requires external power and relay or MOSFET. Pulse energize, don't hold continuously (overheating)." },
  { id: "vibration-motor", name: "Vibration Motor", desc: "3 V pancake haptic, 60 mA, PWM", category: "Output & Display", icon: "Zap", lang: "cpp", interface: "pwm", pinsRequired: 1, voltage: 5, currentDrawMa: 60 },

  // ── Input & User ──
  { id: "push-button", name: "Push Button", desc: "Momentary tactile switch, 4-pin, 12×12 mm", category: "Input & User", icon: "Circle", lang: "both", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 0.1 },
  { id: "keypad-4x4", name: "4×4 Keypad", desc: "16-button matrix membrane, 8 pins", category: "Input & User", icon: "Grid3x3", lang: "cpp", interface: "digital", pinsRequired: 8, voltage: "3.3-5", currentDrawMa: 5 },
  { id: "potentiometer", name: "Potentiometer", desc: "10 kΩ rotary, analog voltage divider", category: "Input & User", icon: "RotateCcw", lang: "both", interface: "analog", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 0.5 },
  { id: "joystick", name: "Joystick", desc: "2-axis analog + button, 5 pins", category: "Input & User", icon: "Gamepad2", lang: "cpp", interface: "analog", pinsRequired: 3, voltage: "3.3-5", currentDrawMa: 10 },
  { id: "touch", name: "Capacitive Touch", desc: "TTP223, touch-to-digital, 2-5 V", category: "Input & User", icon: "Hand", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 2 },
  { id: "rfid-rc522", name: "RFID (RC522)", desc: "13.56 MHz, SPI, 3.3 V, read/write", category: "Input & User", icon: "CreditCard", lang: "cpp", interface: "spi", pinsRequired: 6, voltage: 3.3, currentDrawMa: 15, calibrationNote: "3.3V ONLY — 5V will destroy it. SPI pins: SDA(SS), SCK, MOSI, MISO, IRQ, RST. Range ~3-5cm." },
  { id: "ir-receiver", name: "IR Receiver", desc: "TSOP382, 38 kHz, NEC protocol", category: "Input & User", icon: "Radio", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: "3.3-5", currentDrawMa: 0.5 },
  { id: "sound-sensor", name: "Sound Sensor", desc: "Electret mic + comparator, digital + analog", category: "Input & User", icon: "Mic", lang: "cpp", interface: "analog", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 5 },
  { id: "max4466", name: "Microphone (MAX4466)", desc: "Electret with adjustable gain, analog out", category: "Input & User", icon: "Mic", lang: "cpp", interface: "analog", pinsRequired: 1, voltage: 5, currentDrawMa: 0.15, calibrationNote: "Output is AC-coupled — center voltage is VCC/2. Use ADC to measure amplitude envelope, not raw values." },
  { id: "max30102", name: "Pulse Oximeter (MAX30102)", desc: "Heart-rate + SpO₂, I²C, red/IR LEDs", category: "Input & User", icon: "Activity", lang: "cpp", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 1.2, i2cAddress: "0x57", calibrationNote: "I2C 0x57. Very motion-sensitive — readings unreliable during movement. Requires tight skin contact. Not medical-grade." },

  // ── Connectivity ──
  { id: "hc05", name: "HC-05 Bluetooth", desc: "Bluetooth 2.0, UART, master/slave, 3.3 V", category: "Connectivity", icon: "Bluetooth", lang: "cpp", interface: "uart", pinsRequired: 2, voltage: 3.3, currentDrawMa: 40, calibrationNote: "3.3V logic only — use voltage divider on RX if connected to 5V board. Default baud 9600 (AT mode) or 38400 (data mode)." },
  { id: "nrf24l01", name: "nRF24L01", desc: "2.4 GHz radio, 1 Mbps, SPI, 100 m range", category: "Connectivity", icon: "Radio", lang: "cpp", interface: "spi", pinsRequired: 6, voltage: 3.3, currentDrawMa: 13, calibrationNote: "3.3V ONLY. Requires 100µF cap near VCC for stable operation. PA+LNA version draws up to 115mA — use external 3.3V regulator." },
  { id: "lora-sx1278", name: "LoRa (SX1278)", desc: "868/915 MHz, 3 km+ range, SPI", category: "Connectivity", icon: "Radio", lang: "cpp", interface: "spi", pinsRequired: 6, voltage: "3.3-5", currentDrawMa: 40 },
  { id: "sim800l", name: "SIM800L GSM", desc: "Quad-band GSM/GPRS, 2G, 4 V LiPo", category: "Connectivity", icon: "Smartphone", lang: "cpp", interface: "uart", pinsRequired: 2, voltage: 3.3, currentDrawMa: 500, calibrationNote: "Peak current 2A during GSM transmission — requires 4V/2A supply and large (1000µF) capacitor. 2G network is being phased out in many regions." },
  { id: "neo6m", name: "NEO-6M GPS", desc: "UART, 50 channels, 2.5 m accuracy", category: "Connectivity", icon: "MapPin", lang: "cpp", interface: "uart", pinsRequired: 2, voltage: 3.3, currentDrawMa: 45, calibrationNote: "3.3V logic. Cold start ~27s. Needs clear sky view — unusable indoors. Antenna must face up. Active antenna recommended." },

  // ── Power & Control ──
  { id: "ds3231", name: "DS3231 RTC", desc: "Real-time clock, ±2 ppm, I²C, battery backup", category: "Power & Control", icon: "Clock", lang: "both", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 0.2, i2cAddress: "0x68", calibrationNote: "I2C 0x68. ±2ppm = ~1 minute drift per year. CR2032 backup maintains time when main power off. More accurate than DS1307." },
  { id: "sd-card", name: "SD Card Module", desc: "SPI, 3.3 V, FAT16/FAT32", category: "Power & Control", icon: "Save", lang: "cpp", interface: "spi", pinsRequired: 6, voltage: 5, currentDrawMa: 80, calibrationNote: "3.3V logic — onboard regulator accepts 5V. FAT16/FAT32 only (no exFAT). Write speed ~100KB/s. Remove card before power-off to prevent corruption." },
  { id: "eeprom-24c256", name: "EEPROM (24C256)", desc: "256 Kbit I²C, non-volatile storage", category: "Power & Control", icon: "Database", lang: "cpp", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 0.003, i2cAddress: "0x50", calibrationNote: "I2C 0x50 (default). 100k write cycles. ~5ms write time per page. Address configurable via A0/A1/A2 pins (0x50-0x57)." },
  { id: "tp4056", name: "LiPo Charger (TP4056)", desc: "USB 5 V 1 A single-cell charger", category: "Power & Control", icon: "BatteryCharging", lang: "cpp", interface: "other", pinsRequired: 0, voltage: 5, currentDrawMa: 0 },
  { id: "buck-converter", name: "Buck Converter", desc: "LM2596 adjustable step-down, 3-40 V", category: "Power & Control", icon: "ArrowDownCircle", lang: "cpp", interface: "other", pinsRequired: 0, voltage: "3.3-5", currentDrawMa: 0 },
  { id: "acs712", name: "ACS712 Current", desc: "5 A / 20 A / 30 A hall-effect, analog", category: "Power & Control", icon: "Zap", lang: "cpp", interface: "analog", pinsRequired: 1, voltage: 5, currentDrawMa: 10, calibrationNote: "Output 185mV/A (5A variant) or 100mV/A (20A) or 66mV/A (30A). Center voltage = VCC/2 (zero current). Noise ~20mV peak-peak." },
  { id: "ina219", name: "INA219", desc: "Current/voltage/power monitor, I²C, ±0.5%", category: "Power & Control", icon: "Activity", lang: "cpp", interface: "i2c", pinsRequired: 2, voltage: "3.3-5", currentDrawMa: 1, i2cAddress: "0x40", calibrationNote: "I2C 0x40 (default). Address configurable 0x40-0x4F via A0/A1 pins. Measures bus voltage up to 26V and shunt voltage across sense resistor." },
  { id: "mosfet", name: "MOSFET Module", desc: "IRLZ44N N-channel, 5 V logic gate, 47 A", category: "Power & Control", icon: "ArrowUpCircle", lang: "cpp", interface: "digital", pinsRequired: 1, voltage: 5, currentDrawMa: 0.1 },
];

export const CATEGORIES = [...new Set(COMPONENTS.map((c) => c.category))] as Component["category"][];

export const BOARD_COMPONENTS = COMPONENTS.filter((c) => c.category === "Board");
export const SENSOR_COMPONENTS = COMPONENTS.filter((c) => c.category !== "Board");

export const BOARD_SPECS: BoardSpec[] = [
  { id: "arduino-uno", name: "Arduino Uno", logicVoltage: 5, digitalPins: ["D0","D1","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13"], analogPins: ["A0","A1","A2","A3","A4","A5"], hasI2c: true, hasSpi: true, maxCurrentMa: 500 },
  { id: "arduino-nano", name: "Arduino Nano", logicVoltage: 5, digitalPins: ["D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13"], analogPins: ["A0","A1","A2","A3","A4","A5","A6","A7"], hasI2c: true, hasSpi: true, maxCurrentMa: 500 },
  { id: "arduino-mega", name: "Arduino Mega", logicVoltage: 5, digitalPins: ["D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","D14","D15","D16","D17","D18","D19","D20","D21","D22","D23","D24","D25","D26","D27","D28","D29","D30","D31","D32","D33","D34","D35","D36","D37","D38","D39","D40","D41","D42","D43","D44","D45","D46","D47","D48","D49","D50","D51","D52","D53"], analogPins: ["A0","A1","A2","A3","A4","A5","A6","A7","A8","A9","A10","A11","A12","A13","A14","A15"], hasI2c: true, hasSpi: true, maxCurrentMa: 800 },
  { id: "arduino-pro-mini", name: "Arduino Pro Mini", logicVoltage: 5, digitalPins: ["D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13"], analogPins: ["A0","A1","A2","A3","A4","A5","A6","A7"], hasI2c: true, hasSpi: true, maxCurrentMa: 150 },
  { id: "esp32", name: "ESP32", logicVoltage: 3.3, digitalPins: ["D2","D4","D5","D12","D13","D14","D15","D16","D17","D18","D19","D21","D22","D23","D25","D26","D27","D32","D33","D34","D35","D36","D39"], analogPins: ["D34","D35","D36","D39"], hasI2c: true, hasSpi: true, maxCurrentMa: 250 },
  { id: "esp8266", name: "ESP8266 (NodeMCU)", logicVoltage: 3.3, digitalPins: ["D0","D1","D2","D3","D4","D5","D6","D7","D8"], analogPins: ["A0"], hasI2c: true, hasSpi: true, maxCurrentMa: 200 },
  { id: "rpi4", name: "Raspberry Pi 4", logicVoltage: 3.3, digitalPins: ["GPIO2","GPIO3","GPIO4","GPIO5","GPIO6","GPIO7","GPIO8","GPIO9","GPIO10","GPIO11","GPIO12","GPIO13","GPIO14","GPIO15","GPIO16","GPIO17","GPIO18","GPIO19","GPIO20","GPIO21","GPIO22","GPIO23","GPIO24","GPIO25","GPIO26","GPIO27"], analogPins: [], hasI2c: true, hasSpi: true, maxCurrentMa: 600 },
  { id: "rpi-zero2", name: "Raspberry Pi Zero 2", logicVoltage: 3.3, digitalPins: ["GPIO2","GPIO3","GPIO4","GPIO5","GPIO6","GPIO7","GPIO8","GPIO9","GPIO10","GPIO11","GPIO12","GPIO13","GPIO14","GPIO15","GPIO16","GPIO17","GPIO18","GPIO19","GPIO20","GPIO21","GPIO22","GPIO23","GPIO24","GPIO25","GPIO26","GPIO27"], analogPins: [], hasI2c: true, hasSpi: true, maxCurrentMa: 350 },
  { id: "rpi-pico", name: "Raspberry Pi Pico", logicVoltage: 3.3, digitalPins: ["GP0","GP1","GP2","GP3","GP4","GP5","GP6","GP7","GP8","GP9","GP10","GP11","GP12","GP13","GP14","GP15","GP16","GP17","GP18","GP19","GP20","GP21","GP22","GP26","GP27","GP28"], analogPins: ["GP26","GP27","GP28"], hasI2c: true, hasSpi: true, maxCurrentMa: 300 },
  { id: "stm32-bluepill", name: "STM32 Blue Pill", logicVoltage: 3.3, digitalPins: ["PB0","PB1","PB10","PB11","PB12","PB13","PB14","PB15","PA0","PA1","PA2","PA3","PA4","PA5","PA6","PA7","PA8","PA9","PA10","PA11","PA12","PA15"], analogPins: ["PA0","PA1","PA2","PA3","PA4","PA5","PA6","PA7","PB0","PB1"], hasI2c: true, hasSpi: true, maxCurrentMa: 200 },
];
