// Strip all HTML tags except safe ones generated by renderMarkdown
const ALLOWED = new Set(['strong', 'em', 'br', 'code', 'pre', 'span', 'b', 'i', 'div']);
const ALLOWED_ATTRS = new Set(['class']);

export function sanitizeHtml(html: string): string {
  if (typeof window === 'undefined') return html;
  return html.replace(/<[^>]*>/g, (tag) => {
    const match = tag.match(/^<\/?(\w+)/);
    if (!match) return '';
    const tagName = match[1].toLowerCase();
    if (!ALLOWED.has(tagName)) return '';
    const attrs = tag.match(/(\w+)=["']([^"']*)["']/g);
    if (!attrs) return tag.match(/^\s*<\//) ? `</${tagName}>` : `<${tagName}>`;
    const safe = attrs.filter((a) => ALLOWED_ATTRS.has(a.split('=')[0]));
    return safe.length ? `<${tagName} ${safe.join(' ')}>` : `<${tagName}>`;
  });
}
